/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import main.StateMachine;
import modelo.Pelicula;
import java.time.LocalDateTime;

/**
 *
 * @author seralpa
 */
public class Compra extends javax.swing.JPanel {

    private final CompraController c;
    private Pelicula pelicula;
    private LocalDateTime sesion;
    /**
     * Creates new form Compra
     */
    public Compra(StateMachine state, Pelicula pelicula, LocalDateTime sesion) {
        initComponents();
        c=new CompraController(state,pelicula,sesion,this);
        this.pelicula=pelicula;
        this.sesion=sesion;
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        entradaNormal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sEntradasNormales = new javax.swing.JSpinner();
        entradaNinos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sEntradasNinos = new javax.swing.JSpinner();
        TOTAL = new javax.swing.JLabel();
        jpanel5 = new javax.swing.JPanel();
        precioTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        atras = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        poster = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tituloPeli = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout(0, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona tus entradas");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");

        jPanel1.setPreferredSize(new java.awt.Dimension(318, 130));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 60, 30));

        entradaNormal.setText("Entradas normales    7.00€");
        jPanel1.add(entradaNormal);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        sEntradasNormales.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        sEntradasNormales.setPreferredSize(new java.awt.Dimension(50, 30));
        sEntradasNormales.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sEntradasNormalesStateChanged(evt);
            }
        });
        jPanel3.add(sEntradasNormales, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        entradaNinos.setText("Entradas niños    5.00€");
        jPanel1.add(entradaNinos);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        sEntradasNinos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        sEntradasNinos.setPreferredSize(new java.awt.Dimension(50, 30));
        sEntradasNinos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sEntradasNinosStateChanged(evt);
            }
        });
        jPanel4.add(sEntradasNinos, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4);

        TOTAL.setText("Total");
        jPanel1.add(TOTAL);

        jpanel5.setLayout(new java.awt.GridBagLayout());

        precioTotal.setText("0");
        jpanel5.add(precioTotal, new java.awt.GridBagConstraints());

        jPanel1.add(jpanel5);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        atras.setText("<-Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        jPanel2.add(atras);

        siguiente.setText("Siguiente->");
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        jPanel2.add(siguiente);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        poster.setText("jLabel2");
        jPanel5.add(poster);

        tituloPeli.setText("jLabel5");

        fecha.setText("jLabel6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPeli)
                    .addComponent(fecha))
                .addGap(42, 42, 42))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPeli)
                .addGap(18, 18, 18)
                .addComponent(fecha)
                .addContainerGap())
        );

        jPanel5.add(jPanel6);

        add(jPanel5, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        c.atras();
    }//GEN-LAST:event_atrasMouseClicked

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        c.siguiente();
    }//GEN-LAST:event_siguienteMouseClicked

    private void sEntradasNormalesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sEntradasNormalesStateChanged
        c.updatePrice();
    }//GEN-LAST:event_sEntradasNormalesStateChanged

    private void sEntradasNinosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sEntradasNinosStateChanged
        c.updatePrice();
    }//GEN-LAST:event_sEntradasNinosStateChanged

    public int getSEntradasNormalesValue(){
        return (int)sEntradasNormales.getValue();
    }

    public int getSEntradasNinosValue(){
        return (int)sEntradasNinos.getValue();
    }
    
    public void setPrecioTotal(String text){
        precioTotal.setText(text);
    }
    
    public void update(){
        poster.setIcon(pelicula.getInfo().getPoster());
        tituloPeli.setText(pelicula.getInfo().getNombre());
        fecha.setText(sesion.getDayOfWeek()+"  "+sesion.getMonth()+"/"+sesion.getDayOfMonth()+"\n"+sesion.getHour()+":"+sesion.getMinute());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOTAL;
    private javax.swing.JButton atras;
    private javax.swing.JLabel entradaNinos;
    private javax.swing.JLabel entradaNormal;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jpanel5;
    private javax.swing.JLabel poster;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JSpinner sEntradasNinos;
    private javax.swing.JSpinner sEntradasNormales;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel tituloPeli;
    // End of variables declaration//GEN-END:variables
}
