/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author seralpa
 */
public class Pago extends javax.swing.JPanel {

    private final float IVA=(float)0.21;
    private final PagoController c;
    private final float precio;
    /**
     * Creates new form Pago
     */
    public Pago(PagoController c,float precio) {
        initComponents();
        this.c=c;
        this.precio=precio;
        setPrecioBruto(precio/(1+IVA));
        setIVA(precio*IVA);
        setTotal(precio);
        setPuntos((int)precio/10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tarjetaCredito = new javax.swing.JButton();
        payPal = new javax.swing.JButton();
        criptomoneda = new javax.swing.JButton();
        tarjetaFidelizacion = new javax.swing.JButton();
        numTarjetaFidelizacion = new javax.swing.JTextField();
        validarNum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        precioBruto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione su método de pago");

        tarjetaCredito.setText("jButton1");
        tarjetaCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarjetaCreditoMouseClicked(evt);
            }
        });

        payPal.setText("jButton2");
        payPal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payPalMouseClicked(evt);
            }
        });

        criptomoneda.setText("jButton1");
        criptomoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criptomonedaMouseClicked(evt);
            }
        });

        tarjetaFidelizacion.setText("jButton1");
        tarjetaFidelizacion.setEnabled(false);
        tarjetaFidelizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarjetaFidelizacionMouseClicked(evt);
            }
        });

        validarNum.setText("validar");
        validarNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarNumMouseClicked(evt);
            }
        });

        jLabel2.setText("Introduzca su numero de tarjeta de fidelización");

        jLabel3.setText("para acumular puntos con su compra");

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Flecha.png"))); // NOI18N
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });

        jLabel4.setText("Precio sin IVA: ");

        precioBruto.setText("0€");

        jLabel6.setText("IVA (21%):");

        iva.setText("0€");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("TOTAL:");

        precioTotal.setText("0€");

        jLabel5.setText("Puntos:");

        puntos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numTarjetaFidelizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validarNum))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atras)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tarjetaCredito)
                        .addComponent(payPal)
                        .addComponent(criptomoneda)
                        .addComponent(tarjetaFidelizacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioTotal)
                    .addComponent(iva)
                    .addComponent(precioBruto)
                    .addComponent(puntos))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTarjetaFidelizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validarNum))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tarjetaCredito)
                        .addGap(18, 18, 18)
                        .addComponent(payPal)
                        .addGap(18, 18, 18)
                        .addComponent(criptomoneda))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(precioBruto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(iva))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(precioTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(puntos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjetaFidelizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(atras)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tarjetaCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjetaCreditoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCreditoMouseClicked

    private void payPalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payPalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_payPalMouseClicked

    private void criptomonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criptomonedaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_criptomonedaMouseClicked

    private void validarNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarNumMouseClicked
        c.validarNum();
    }//GEN-LAST:event_validarNumMouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasMouseClicked

    private void tarjetaFidelizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjetaFidelizacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaFidelizacionMouseClicked

    public String getNum(){
        return numTarjetaFidelizacion.getText();
    }
    
    public void setPrecioBruto(float p){
        precioBruto.setText(p+"€");
    }
    
    public void setIVA(float p){
        iva.setText(p+"€");
    }
    
    public void setTotal(float p){
        precioTotal.setText(p+"€");
    }
    
    public void setPuntos(int p){
        puntos.setText(p+"");
    }
    
    public void setTarjetaFidelizacionON(){
        tarjetaFidelizacion.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton criptomoneda;
    private javax.swing.JLabel iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField numTarjetaFidelizacion;
    private javax.swing.JButton payPal;
    private javax.swing.JLabel precioBruto;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JLabel puntos;
    private javax.swing.JButton tarjetaCredito;
    private javax.swing.JButton tarjetaFidelizacion;
    private javax.swing.JButton validarNum;
    // End of variables declaration//GEN-END:variables
}
